name: Image Security Analysis

on:
  workflow_call:

jobs:
  trivy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: docker-image
          path: /tmp

      - name: Load image
        run: docker load -i /tmp/image.tar

      - uses: aquasecurity/trivy-action@0.36.0
        continue-on-error: true
        with:
          input: /tmp/image.tar
          format: sarif
          output: trivy-results.sarif
          severity: CRITICAL,HIGH

      - uses: github/codeql-action/upload-sarif@v4
        if: always()
        with:
          sarif_file: trivy-results.sarif
